INSTALL_DIR = /g/g90/sato5/lib/libibtl-install

ibio_test_OBJS = ibio_test.o ibio_client.c ibio_common.c
ibio_test_PROGRAM = ibio_test

ibio_server_OBJS = ibio_server.o ibio_common.o yarn.o pgz.o
ibio_server_PROGRAM = ibio_server

PROGRAMS= $(ibio_test_PROGRAM) $(ibio_server_PROGRAM)
OBJS= $(ibio_test_OBJS) $(ibio_server_OBJS)

CC = gcc
LDFLAGS = -I/usr/include/ -I$(INSTALL_DIR)/include  -L/usr/lib64/   -L$(INSTALL_DIR)/lib  -lrdmacm -lpthread -lz -libtls
CFLAGS = -Wall -O2

.SUFFIXES: .c .o

all: $(ibio_test_PROGRAM)  $(ibio_server_PROGRAM) 

$(ibio_test_PROGRAM): $(ibio_test_OBJS)
		    $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

$(ibio_server_PROGRAM): $(ibio_server_OBJS)
			   $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

.c.o: 
	$(CC) $(CFLAGS) $(LDFLAGS) -c $<

.PHONY: clean
clean:
	rm -rf $(PROGRAMS) $(OBJS)