INSTALL_DIR = /g/g90/sato5/lib/libibtl-install

ibtl_io_OBJS = ibtl_io.o ibtl_io_client.c ibvio_common.c
ibtl_io_PROGRAM = ibtl_io

ibtl_io_server_OBJS = ibtl_io_server.o ibvio_common.o yarn.o pgz.o
ibtl_io_server_PROGRAM = ibtl_io_server

PROGRAMS= $(ibtl_io_PROGRAM) $(ibtl_io_server_PROGRAM)
OBJS= $(ibtl_io_OBJS) $(ibtl_io_server_OBJS)

CC = gcc
LDFLAGS = -I/usr/include/ -I$(INSTALL_DIR)/include  -L/usr/lib64/   -L$(INSTALL_DIR)/lib  -lrdmacm -lpthread -lz -libtls
CFLAGS = -Wall -O2

.SUFFIXES: .c .o

all: $(ibtl_io_PROGRAM)  $(ibtl_io_server_PROGRAM) 

$(ibtl_io_PROGRAM): $(ibtl_io_OBJS)
		    $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

$(ibtl_io_server_PROGRAM): $(ibtl_io_server_OBJS)
			   $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

.c.o: 
	$(CC) $(CFLAGS) $(LDFLAGS) -c $<

.PHONY: clean
clean:
	rm -rf $(PROGRAMS) $(OBJS)